### ISSUE TITLE
babo

### ISSUE THREAD

**Issue by jiwonkim0131** [jiwonkim0131/TIL#1]
# 이미지 최적화
3조 : 김윤회,김지원,이정훈,이효원

- 목차
    1. [이미지 최적화란?](#-1.-이미지-최적화란?)
    2. [이미지 최적화의 필요성](#-2.-이미지-최적화의-필요성)
        a. 페이지 로딩 속도 줄이기(사용자 경험 향상)
        b. SEO(검색 엔진 최적화)
        c. 비용
    3. 이미지 최적화 방법
        a.HTML에서의 이미지 최적화
         - 이미지에 상대 크기 사용
            - srcset
            - 아트디렉션
        b. CSS에서의 이미지 최적화
            - 조건부 이미지 로딩 또는 아트 디렉션에 미디어쿼리 사용
            - image-set() 사용
            - 아이콘 이미지 최적화
        c. 그 외 이미지 최적화 방법들
            - 올바른 형식 선택
            - 파일크기 줄이기
    4. 이미지 최적화 테스트
    5. 출처 및 참고자료

# 1. 이미지 최적화란?
- 이상적인 포맷과 사이즈, 그리고 해상도로 고품질의 이미지를 만들어 사용자 참여를 향상시키는 프로세스.
- 웹사이트나 블로그에 업로드된 이미지를 SEO 및 웹사이트 방문율 증가에 도움이 되도록 이미지에 정확하게 라벨링을 하는 작업도 포함된다.
</br>

# 2. 이미지 최적화의 필요성
### 2.1.1 웹 페이지에서 이미지가 차지하는 용량 비율
![이미지최적화 통계](https://user-images.githubusercontent.com/48905932/130340506-b2969926-fb75-41fc-ace2-60c60425f4ca.png)
- HTTP 아카이브에 따르면 이미지는 2018년 11월 기준으로 전체 웹페이지 내에서 평균적으로 21% 가량 비중을 차지.

    -> 이미지는 웹사이트의 다른 요소보다 많은 용량을 차지하기 때문에 크기와 복잡성이 사이트에 크게 영향을 준다.

    -> 따라서 페이지 로딩에 있어서 매초가 중요.
</br>

### 2.1.2 페이지 로딩과 사용자 참여의 상관관계
![Untitled-1](https://user-images.githubusercontent.com/48905932/130340671-0fd11890-88fa-4dc5-b144-5b979e4ee4e1.png)
- 에버딘그룹의 연구에 따르면 페이지 로딩 시간이 1초 지연될 때마다 전환이 7% 감소, 또한 페이지 로딩 시간이 3초 지연될 때마다 웹사이트 방문자의 40%가 이탈한다.

![image](https://user-images.githubusercontent.com/48905932/130344379-d966cdec-73a2-4062-855c-55f8fbc571f9.jpeg)
- [Soasta/Google 연구](https://www.thinkwithgoogle.com/marketing-strategies/app-and-mobile/mobile-page-speed-load-time/)에 따르면, 전환율에서 이미지가 2번째로 중요한 역할을 합니다. 또한, 이미지 수가 기존 대비 38% 정도 줄은 페이지에서 가장 전환율이 높다.

    -> 이미지 최적화를 통해 사용자에게 신속한 디스플레이를 제공해야 한다.
</br>

## 2.2 SEO(검색 엔진 최적화)
[Google 이미지 권장사항](https://developers.google.com/search/docs/advanced/guidelines/google-images?hl=ko)
- Google과 같은 검색엔진은 정교한 알고리즘을 이용해 웹 사이트 순위를 결정한다.
- 사용자 환경의 향상과 사이트와의 인터렉션은 검색 엔진 순위에 긍정적인 영향을 미치므로 고객 참여, 전환, 그리고 고객 재구매율이 향상된다.
- 이미지는 검색엔진에 중요한 문맥 정보를 제공하며, 최적회된 이미지는 사용자 참여와 경험에 긍정적인 역할을 한다.
- 따라서 이미지 최적화를 통해 사용자의 웹사이트 참여율과 페이지 성능을 높일 경우, 검색 엔진 최적화 효과를 기대할 수 있다.
</br>

## 2.3 비용
- 서버의 저장공간이 적게 필요하게 되어, 비용 절감으로 이어진다.
- 웹 호스팅 시 페이지의 크기를 줄여서 대역폭을 적게 사용하여 호스팅 비용을 감소시킨다.
</br>

# 3. 이미지 최적화 방법
이미지 최적화 작업은 파일 크기를 줄이는 다양한 방법을 사용하여 진행된다. 
다음의 이미지 최적화 기법들 중에서 서비스에서 필요한 이미지의 해상도, 유형에 따라 적절한 최적화 방법을 선택해 진행할 수 있다.

![jjjj](https://user-images.githubusercontent.com/48905932/130344553-d5cdfd45-306e-4c27-9719-2f44ec835a71.jpeg)

다양한 이미지 최적화 방법을 아래와 같이 그룹화하여 정리해보았다.
![이미지최적화목차](https://user-images.githubusercontent.com/48905932/130342998-56a17d61-1079-428a-ae9c-cb3aa5fef124.png)
</br>

### 3.1.1 이미지에 상대 크기 사용
```css
img, embed, object, video {
    max-width: 100%;
}
```
* 이미지에 대해 상대 크기를 사용하면 실수로 이미지가 컨테이너를 overflow 하는 것을 막을 수 있다.
* CSS에서는 콘텐츠가 컨테이너를 overflow하도록 허용하므로, 이미지와 기타 콘텐츠가 overflow 되는 것을 막으려면 max-width: 100%를 사용하여 문제를 해결할 수 있다.
</br>

### 3.1.2 `srcset`로 이미지 개선
* srcset 속성은 '이미지 소스의 세트'라는 의미로, img 요소의 동작을 향상시켜주며, 다른 기기 속성에 대해 여러 가지 이미지 파일을 쉽게 제공활 수 있다.
* srcset을 사용하면 브라우저가 기기 특성에 따라 최적의 이미지를 선택할 수 있다.
* srcset을 지원하지 않는 브라우저에서는 src 속성에 의해 지정된 기본 이미지 파일을 사용한다. 이러한 이유 때문에, 성능에 상관없이 모든 기기에 표시될 수 있는 1x 이미지를 항상 포함하는 것이 중요하다.
* srcset이 지원되는 경우 모든 요청을 수행하기 전에, 쉼표로 구분된 이미지/조건 목록이 분석되며, 가장 적절한 이미지만 다운로드되어 표시된다.
</br>

### 상대 크기의 이미지
이미지의 최종 크기를 알 수 없는 경우, 이미지 소스의 밀도 설명자를 지정하기 어려울 수 있다. 브라우저의 크기에 따라 브라우저의 비례 너비가 유동적으로 변하는 경우 특히 더 어렵다. 고정된 크기의 이미지와 밀도를 제공하는 대신, 이미지 요소 크기와 함께 w 디스크립터를 추가하여 각 이미지의 크기를 지정할 수 있다.

```html
<img src="image-200.jpg" sizes="50vw"
     srcset="image-100.jpg 100w, image.jpg 200w,
             image-400.jpg 400w, image-800.jpg 800w,
             image-1000.jpg 1000w, image-1400.jpg 1400w,
             image-1800.jpg 1800w" alt="image description" />
```
* 브라우저 너비와 기기 픽셀 비율에 따라 뷰포트 너비의 절반인 이미지를 렌더링하므로, 브라우저 창 크기에 관계없이 올바른 이미지를 선택할 수 있다.
</br>

### 반응형 이미지에서 중단점 고려
많은 경우에, 사이트의 레이아웃 중단점에 따라 이미지 크기가 변경될 수 있다. 예를 들어, 작은 화면에서는 뷰포트의 전체 너비에 맞게 이미지가 확대되는 것이 좋지만, 큰 화면에서는 이미지가 작은 부분만을 차지해야 한다.

```html
<img src="400.png"
     sizes="(min-width: 768px) 25vw, (min-width: 360px) 50vw, 100vw"
     srcset="100.png 100w, 200.png 200w, 400.png 400w,
             800.png 800w, 1600.png 1600w, 2000.png 2000w" alt="image description">
```
* 브라우저 너비가 768px 이상인 경우 이미지는 뷰포트 너비의 25%가 된다.
* 360px ~ 768px인 경우 이미지는 뷰포트 너비의 50%가 된다.
* 360px 미만인 경우 이미지는 전체 너비가 된다.
</br>

### 3.1.3 아트디렉션
사용자에게 최선의 화질로 이미지를 전달하는 것도 중요하지만, 때에 따라서는 사이트를 아트 디렉션의 관점에서(디자인적인 관점에서) 생각해 볼 필요도 있다. 만약 사용자 화면 크기가 작아진다면, 가용 공간을 최대한 활용하여 이미지를 자르거나 확대하여 보여주고 싶을 수도 있다.
→ 즉, 가용 공간을 최대한 잘 활용하기 위해 각각의 break point 마다 이미지가 다르게 보이도록 조정된다. 
- [아트디렉션 체험하기](https://responsive-images-art-direction.glitch.me)
</br>

### `picture` 요소를 사용한 반응형 이미지에서의 아트디렉션
* 기기 해상도에 따라 이미지를 변경하려면(아트 디렉션) picture 요소를 사용한다. picture 요소는 기기 크기나 해상도, 방향에 따라 여러 버전의 이미지를 제공하기 위한 선언적 솔루션을 정의한다.
* 이미지 소스가 여러가지 밀도로 존재하는 경우 또는 반응형 디자인에 따라 약간 다른 이미지가 표시되는 경우 picture 요소에 여러 source 요소를 포함하는 방법으로 미디어 쿼리 또는 이미지 형식에 따라 다른 이미지 파일을 지정할 수 있다.

```html
<picture>
    <source media="(min-width: 768px)" srcset="image.jpg, image-2x.jpg 2x">
    <source media="(min-width: 360px)" srcset="image-small.jpg, image-small-2x.jpg 2x">
    <img src="image-fb.jpg" srcset="image-fb-2x.jpg 2x" alt="image description">
</picture>
```
* 위의 예시에서 브라우저 너비가 768px 이상이면 기기 해상도에 따라 image.jpg 또는 image-2x.jpg가 사용된다.
* 브라우저 너비가 360px에서 768px 사이이면 다시 기기 해상도에 따라 image-small.jpg 또는 image-small-2x.jpg가 사용된다. 
* 360px 미만인 화면 너비의 경우 picture 요소가 지원되지 않는 이전 버전과의 호환성을 위해, 브라우저는 대신 img 요소를 렌더링해야 한다.
</br>

### 아트 디렉션 실습
세 가지 스크린 크기에 맞는 이미지를 준비하여 적용되는 이미지 변화를 확인해보았다.

```html
<body>
        <header>
            <h1>Image optimization Test with artDirection </h1>
            <h2>🤔Let's check out how the image changes.👀</h2>
        </header>
        <picture>
            <source media="(max-width: 600px)" srcset="../artDirection_test/images/lyan-square.png">
            <source media="(max-width: 1023px)" srcset="../artDirection_test/images/lyan-rectangle.png">
            <source media="(min-width: 1024px)" srcset="../artDirection_test/images/lyan-desktop.png">    
            <img src="../artDirection_test/images/lyan-desktop.png">
        </picture>
</body>
```
</br>

**1. width : 1920**
![아트디렉션_1920](https://user-images.githubusercontent.com/61184798/130343099-ac5608c7-8151-4b16-a89e-93c4676f48ff.png)

* 뷰포트 최대 너비에서 네트워크를 확인한 결과, min-width: 1024px 조건에 걸려서 lyan-desktop.png 이미지가 적용된 것이 확인되었다.
</br>

**2. width : 720**
![아트디렉션_720](https://user-images.githubusercontent.com/61184798/130343096-d80dc3aa-139b-487d-8fae-a31ac315ae9e.png)

* 뷰포트 너비를 720으로 줄이고 네트워크를 확인한 결과, width가 600px보다 크고 1024보다 작다는 조건에 부합하여 lyan-rectangle.png 이미지 파일이 적용된 것이 확인되었다.
</br>

**3. width : 600**
![아트디렉션_600](https://user-images.githubusercontent.com/61184798/130343092-e784aa22-7254-43a2-82d5-b0fbac59f250.png)

* width를 600까지 줄였을 때는 lyan-square.png 이미지 파일이 적용되었다.
</br>

### 결론  
화면의 크기가 변할 때마다 이미지가 단순히 비율에 따라 줄어드는 것이 아니라 크롭되면서 보여지는 이미지 파일이 변화한다.  
아트디렉션을 활용하여 한정된 화면 크기내에서 이미지의 중요한 부분이나 강조하고 싶은 부분들을 잘 나타낼 수 있다.
</br>

### 3.2.1 조건부 이미지 로딩 또는 아트 디렉션에 미디어쿼리 사용
- 미디어 쿼리를 통해 페이지 레이아웃 뿐만 아니라, 조건부로 이미지를 로드하거나 뷰포트 크기에 따라 아트 디렉션을 제공할 수 있다.
- 미디어쿼리를 이용한 이미지 최적화의 경우 대부분의 브라우저에서 지원한다.
- 미디어쿼리의 대체 방안으로는 CSS의 `image-set()`이 있으나, `image-set()`을 지원하지 않는 브라우저들도 있어 주의해야 한다.
 </br>

### 미디어쿼리를 이용한 이미지 최적화 실습
모바일, 태블릿, 데스크탑용 이미지를 전부 다른 크기,용량으로 준비한 뒤, 스크린 크기에 따른 배경 이미지와, 적용 속도 변화를 비교해보았다.
</br>

1. 이미지 최적화를 하지 않은 경우 : 스크린의 크기가 변해도 background-image에 지정된 이미지가 고정적으로 표시되는 것을 확인하였다.
```css
body {
    background-position: center center;
    background-attachment: fixed;
    background-repeat: no-repeat;
    background-size: cover;
    background-image: url(images/background-desktop.jpg);
}
```
</br>

2. 미디어쿼리를 이용하여 디바이스 크기에 따라 break-point를 지정 : 스크린 크기에 따라 다른 이미지가 로드되는 것을 확인할 수 있다.

```css

body {
    background-position: center center;
    background-attachment: fixed;
    background-repeat: no-repeat;
    background-size: cover;
    /* background-image: url(images/background-desktop.png); */
}


/* 모바일 */
@media (max-width: 480px) {
    body {
        background-image: url(images/background-mobile.png);
    }
}

/* 타블렛 */
@media (min-width: 481px) and (max-width: 1024px) {
    body {
        background-image: url(images/background-tablet.png);
    }
}

/* 데스크탑 */
@media (min-width: 1025px) {
    body {
	    background-image: url(images/background-desktop.png);
   }
}
```
</br>

- max-width : 480인 경우 (모바일)
-> `background-desktop-low_final.jpg` 파일이 적용되며, 로드 속도는 `1ms`
![미디어쿼리_480](https://user-images.githubusercontent.com/48905932/130343219-3ca8139c-98a6-463d-aae1-b75dda6df210.png)
</br>

- max-width : 720인 경우 (태블릿)
-> `background-desktop_mid.jpg` 파일이 적용되며, 로드 속도는 `2ms`
![미디어쿼리_720](https://user-images.githubusercontent.com/48905932/130343409-cc46cc64-b688-43d0-a699-3ffaf69d5c04.png)
</br>

- min-width : 1025인 경우 (데스크탑)
-> `background-desktop.jpeg` 파일이 적용되며, 로드 속도는 `4ms`
![미디어쿼리_1025](https://user-images.githubusercontent.com/48905932/130343413-100472fb-1688-414e-8e97-cfe22437ca57.png)
</br>
    
### 결론
기기의 스크린 사이즈를 미디어 쿼리가 감지하고 크기에 맞는 이미지를 로드해주는 방식으로, 이미지를 최적화할 수 있다.
</br>

### 3.2.2 image-set() 사용
- image-set()은 동작 background 속성을 개선하여 다양한 기기 특성에 맞는 여러 이미지 파일을 쉽게 제공한다.
- 따라서 기기 특성에 따라 브라우저가 최적의 이미지를 선택할 수 있다.(예: 2x 디스플레이에서 2x 이미지를 사용하거나, 제한된 대역폭 네트워크의 경우 2x 기기에서 1x 이미지를 사용).
- image-set() 지원 브라우저 : webkit 공급업체 접두사가 있는 Chrome 및 Safari.
- 따라서 image-set()을 이용한 이미지 최적화는, fallback을 통해 image-set을 지원하지 않는 브라우저까지 고려해야한다.
<img width="354" alt="dddd" src="https://user-images.githubusercontent.com/48905932/130344196-3f0bbfae-0109-4676-9b26-5c052220ca1c.png">

```css
.sample {
  width: 128px;
  height: 128px;
  background-image: url(icon1x.png);
  background-image: -webkit-image-set(  
    url(icon1x.png) 1x,  
    url(icon2x.png) 2x  
  );  
  background-image: image-set(  
    url(icon1x.png) 1x,  
    url(icon2x.png) 2x  
  );
}
```
</br>

### 3.2.3 아이콘 이미지 최적화
아이콘을 페이지에 추가할 때, 가능하면 래스터 이미지 대신 SVG 아이콘을 사용하거나 유니코드 문자를 사용한다. 

### 1. 간단한 아이콘은 유니코드로 대체한다. 
- 상당수 글꼴들은 수많은 유니코드 문자 모양을 지원하기 때문에 이미지 대신 아이콘으로 사용할 수 있다. 
- 이미지와 달리 유니코드 글꼴은 큰 화면이든 작은 화면이든 상관없이 보기가 좋고 확장성이 좋다.
```css
You're a super &#9733;
/* You're a super ★ */
```
</br>

### 2. 복잡한 아이콘은 SVG로 대체한다.
- SVG 아이콘은 일반적으로 용량이 작고, 사용이 쉽고, CSS로 스타일링이 가능하다. 

### SVG 이미지의 장점

![svg](https://user-images.githubusercontent.com/48905932/130343893-652c6d05-2296-44df-8c7d-24a3056f7e68.png)

- SVG는 무한 확장이 가능한 벡터 그래픽.
    → 어떤 디바이스 크기에서도 깨지지 않는다.

- 색상, 음영, 투명도 및 애니메이션과 같은 CSS 효과 적용이 간단하고, 문서에서 바로 인라인 처리될 수 있다.
    → 마크업 언어로 이루어져 css와 js로 바로 수정할 수 있다.

- 문맥적이다.
- 적절한 속성으로 더 나은 접근성을 제공
- 출력이 빠르다.
    →  브라우저는 로딩할 때 마다 서버에 HTTP를 요청해야 함. 웹 페이지에 이미지가 많을수록 더 많은 HTTP요청이 이루어지고, 사이트 속도가 느려진다. SVG 이미지는 크기가 작을뿐만 아니라 HTML의 인라인에 포함하여 HTTP요청을 제거할 수 있어 속도가 빨라진다.
</br>

### 3. 아이콘 글꼴 사용 주의
- FontAwesome과 같은 아이콘 글꼴은 널리 사용되고 사용이 쉽지만, SVG 아이콘에 비해 몇 가지 단점이 있다.
    1. 무한 확장이 가능한 벡터 그래픽이지만, 앤티앨리어싱으로 인해 예상보다 아이콘이 선명하지 않을 수 있다.
    2. CSS를 사용한 스타일 지정이 제한됨.
    3. 선 높이, 글자 간격 등에 따라 완벽한 픽셀 배치가 어려울 수 있다.
    4. 문맥적이 아니며, 스크린 리더 또는 기타 보조 기술과 함께 사용하기가 어려울 수 있다.
    5. 범위가 잘못 지정될 경우, 제공되는 아이콘의 일부만을 사용하기 위해 파일 크기가 커질 수 있다.

- 폰트 어썸 사용 사례 : OKKY 사이트
<img width="721" alt="444" src="https://user-images.githubusercontent.com/48905932/130344276-7932ddf2-a86e-4a98-8e52-1581df5b244b.png">
</br>

### 결론
추가적인 HTTP 요청 및 파일 크기와 아이콘의 필요성 간에 균형을 맞춰 사용하는 것이 좋다. 
예를 들어, 아이콘이 조금만 필요한 경우에는 이미지 또는 image sprite를 사용하는 것이 더 나을 수 있다.
</br>

## 3.3 그 외 성능을 위한 이미지 최적화 방법들
- 이미지를 최적화하면 바이트를 최대한 절약할 수 있고 웹사이트에 맞게 성능을 개선할 수 있다. 
- 또한 브라우저가 다운로드해야 하는 바이트가 줄어들고, 고객의 대역폭에 여유가 생기고, 브라우저가 이미지를 더 빨리 다운로드하고 표시할 수 있다. 
</br>

### 3.3.1 올바른 형식 선택
두 가지 유형의 이미지, 즉 벡터 이미지 및 래스터 이미지를 고려. 래스터 이미지의 경우에는 또한 올바른 압축 형식을 선택한다.
- 사진 이미지에는 JPG를 사용.
- 로고 및 라인 아트와 같은 벡터 아트 및 단색 그래픽에는 SVG를 사용하고, 벡터 아트를 사용할 수 없는 경우 WebP 또는 PNG를 사용한다.
- GIF 대신 더 많은 색상을 허용하고 더 나은 압축율을 제공하는 PNG를 사용한다.
- 길이가 긴 애니메이션의 경우, `<video>`를 사용하면 화질이 향상되고 사용자가 재생을 제어할 수 있다.
</br>

### 3.3.2 파일 크기 줄이기
- 무손실 압축이 가능한 tool을 이용하여 이미지의 용량을 줄여 사용한다.

    `JPG`압축 tool
    - [http://jpegclub.org/](http://jpegclub.org/)
    - [http://freshmeat.sourceforge.net/projects/jpegoptim/](http://freshmeat.sourceforge.net/projects/jpegoptim/)

    `PNG`압축 tool
    - [http://optipng.sourceforge.net/](http://optipng.sourceforge.net/)
    - [http://www.advsys.net/ken/util/pngout.htm](http://www.advsys.net/ken/util/pngout.htm)
</br>

### 3.3.3 image sprite 사용하기
- CSS 스프라이트는 여러 이미지를 한 장으로 묶은 후 CSS의 배경 포지셔닝을 통해 처리하는 기법.
- 웹 페이지에 사용되는 여러 이미지를 하나하나 HTTP 요청을 통해 불러온다면 용량이 아무리 작다 해도 브라우저의 최대 동시 요청수 제한으로 인해 적지 않은 시간이 소요된다.

    `브라우저 별 최대 동시 요청수`
    - 인터넷 익스플로러 7.0 = 2회
    - 인터넷 익스플로러 11.0 = 13회
    - 파이어폭스 = 6회
    - 사파리 = 6회
    - 크롬 = 6회
    - 오페라, IOS, 안드로이드 내장 브라우저 = 6회

- 따라서 여러 이미지들을 한 이미지로 모아 관리하면, 브라우저는 단 한 번의 HTTP 요청만으로 여러 이미지를 한꺼번에 로드해 사용할 수 있다.
- 하지만, 이 방식은 언제나 CSS를 통해 픽셀 단위로 이미지를 관리해야 하므로 더이상 추가되거나 수정될 일이 적은 리소스에 적합하다.

- 현재 네이버 메인페이지에 사용되고있는 버튼 스프라이트 이미지 예시 : 공통 이미지로 설정 한 뒤, 배경의 위치만 조정하고 있다.

![1111](https://user-images.githubusercontent.com/48905932/130344026-925301a7-8323-4054-bd91-c448c654a8be.png)

```css
.ly_inputko .btn_kor {
	position: absolute;
	top: 40px;
	left: 11px;
	z-index: 1;
	width: 22px;
	height: 10px;
	background: url(https://ssl.pstatic.net/sstatic/search/img3/btn_sp_v3.png) no-repeat -380px -40px;
}

.ly_inputko .btn_kor_on {
	position: absolute;
	top: 40px;
	left: 11px;
	z-index: 1;
	width: 22px;
	height: 10px;
	background: url(https://ssl.pstatic.net/sstatic/search/img3/btn_sp_v3.png) no-repeat -420px -40px;
}

.ly_inputko .btn_eng {
	position: absolute;
	top: 40px;
	left: 43px;
	width: 22px;
	height: 10px;
	background: url(https://ssl.pstatic.net/sstatic/search/img3/btn_sp_v3.png) no-repeat -380px -60px;
}

.ly_inputko .btn_eng_on {
	position: absolute;
	top: 40px;
	left: 43px;
	width: 22px;
	height: 10px;
	background: url(https://ssl.pstatic.net/sstatic/search/img3/btn_sp_v3.png) no-repeat -420px -60px;
}
```
</br>

- ✨image sprite 자동화를 도와주는 tools✨

    - [CSS Sprite Generator](https://spritegen.website-performance.org/)</br>
    - [toptal CSS Sprite Generator](https://www.toptal.com/developers/css/sprite-generator)</br>
</br>

# 이미지 최적화 테스트
1. [WebPageTest](https://webpagetest.org/) : 확인하고 싶은 사이트의 주소를 입력 후, `Compress Images` 섹션에서 더 효율적으로 압축할 수 있는 이미지 목록과, 압축 후에 줄일 수 있는 파일 사이즈에 대한 추정치를 확인할 수 있다.

- 네이버 테스트 결과</br>
    <img width="1147" alt="스크린샷 2021-08-22 오후 3 39 18" src="https://user-images.githubusercontent.com/48905932/130345218-abc1f98a-5fbe-4a88-a818-56555ba8e1fb.png">
</br>

- 네이버 페이지 리퀘스트 구성 비율</br>
    <img width="1158" alt="스크린샷 2021-08-22 오후 3 39 23" src="https://user-images.githubusercontent.com/48905932/130345220-09e764eb-1e93-44d9-a4bf-9f0749c8f1e1.png">
</br>

- 네이버 페이지 성능 보고서의 `Compress Images` 섹션</br>
    ![images](https://user-images.githubusercontent.com/48905932/130350428-277d84f7-d3fa-4680-b686-9e6471d546b3.png)
</br>

2. [Google Lighthouse](https://developers.google.com/web/tools/lighthouse/) : 성능 모범 사례를 얼마나 따랐는지 검사할 수 있다. 이미지 최적화 품질에 대한 검사 기능이 포함되어 있으며, 압축의 여지가 남아 있거나 화면에 나오지 않아 레이지로딩 할 수 있는 이미지들을 확인할 수 있다.
</br>

# 출처 및 참고자료
- [Google 검색 센터](https://developers.google.com/search/docs/advanced/guidelines/google-images?hl=ko)
- [Google developers](https://developers.google.com/web/fundamentals/design-and-ux/responsive/images)
- [Soasta/Google 연구](https://www.thinkwithgoogle.com/marketing-strategies/app-and-mobile/mobile-page-speed-load-time/)
- [ABERDEEN 연구](https://www.aberdeen.com/techpro-essentials/gone-in-three-seconds-your-customers-have-no-patience-for-a-slow-website/)
- [mdn 반응형 이미지](https://developer.mozilla.org/ko/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images)
- [SEO를 위한 이미지 최적화](https://www.hedleyonline.com/ko/blog/seo-image-optimization/)
- [webp](https://armadillo-dev.github.io/html/css/image-optimizing-using-webp/)
- [ESSENTIAL IMAGE OPTIMIZATION](https://essential-image-optimization.firebaseapp.com/)
